/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.oz.javarx;

import io.reactivex.rxjava3.core.Observable;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {
        Observable.just(new String[] { "Hello", "World" })
            .subscribe(messages -> Arrays.stream(messages).forEach(System.out::println));
    }
}
